wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1706541371.651
    t:
      1:
      - 1
      - 41
      - 51
      - 55
      - 79
      2:
      - 1
      - 41
      - 51
      - 55
      - 79
      3:
      - 23
      4: 3.8.18
      5: 0.16.2
      8:
      - 3
      - 5
      13: windows-amd64
